package:
  name: smartSlurm
  version: 1.2

source:
  git_url: https://github.com/ld32/smartSlurm.git
  git_rev: master

requirements:
  build:
    - bash
  run:
    - bash

about:
  home: https://github.com/ld32/smartSlurm
  license: MIT
  summary: Making Slurm works smarter
